<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="description" content="A little break. A good game. Play Hangman and Blackjack instantly, with five free rounds of each."><title>{{ ['hangman'=>'Hangman','blackjack'=>'Blackjack','daily'=>'Daily Word','tictactoe'=>'Tic Tac Toe','fade'=>'Fade Tac Toe'][$game] }} · Pocket Arcade</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/arcade.css"><script src="/arcade.js" defer></script></head>
<body data-game="{{ $game }}">
<header><a href="/" class="brand" aria-label="Pocket Arcade home"><span class="brandmark">p<span>•</span></span>pocket<span class="brand-light">arcade</span></a><div class="header-right"><span class="guest" id="account-label">Just you. No sign-up.</span><button class="button small unlock-button" data-unlock>Unlock unlimited <span>$1</span></button></div></header>
@include('social')

<main>
<div class="play-navigation"><a href="/">← All games</a><nav aria-label="Games"><a href="/games/hangman" @if($game==='hangman') aria-current="page" @endif>Hangman</a><a href="/games/blackjack" @if($game==='blackjack') aria-current="page" @endif>Blackjack</a><a href="/games/daily" @if($game==='daily') aria-current="page" @endif>Daily Word</a><a href="/games/tictactoe" @if($game==='tictactoe') aria-current="page" @endif>Tic Tac Toe</a><a href="/games/fade" @if($game==='fade') aria-current="page" @endif>Fade Tac Toe</a><a href="/games/dots">Dots and Boxes</a></nav></div>
@if(in_array($game,['blackjack','tictactoe','fade']))<div class="solo-multi"><span>You’re playing solo.</span><a href="/multiplayer?game={{ $game }}" class="button secondary">Play with friends ↗</a></div>@endif
<section class="game-shell" aria-labelledby="game-title"><div class="play-panel"><div class="game-top"><div><p class="eyebrow" id="game-category">THE WORD CLASSIC</p><h2 id="game-title">{{ ['hangman'=>'Hangman','blackjack'=>'Blackjack','daily'=>'Daily Word','tictactoe'=>'Tic Tac Toe','fade'=>'Fade Tac Toe'][$game] }}</h2></div><span class="round-badge" id="round-badge">Ready when you are</span></div>
<div id="hangman-view" @if($game!=='hangman') hidden @endif><div class="start-line"><button id="hangman-start" class="button primary">Let's play <span>↗</span></button><span id="hangman-help">Your keyboard works here, too.</span></div><div class="hangman-board"><svg viewBox="0 0 260 245" class="gallows" role="img" aria-label="Hangman figure"><path class="frame" d="M30 222 H200 M66 222 V25 H170 V53 M66 60 L101 25"/><g id="figure"><circle data-part="1" cx="170" cy="76" r="23"/><path data-part="2" d="M170 99 V157"/><path data-part="3" d="M170 112 L135 135"/><path data-part="4" d="M170 112 L205 135"/><path data-part="5" d="M170 157 L140 192"/><path data-part="6" d="M170 157 L200 192"/><path data-part="7" d="M160 71 L164 76 M164 71 L160 76"/><path data-part="8" d="M177 71 L181 76 M181 71 L177 76"/></g></svg><div class="word-side"><p id="word-caption">A mystery word is waiting.</p><div class="word" id="word" aria-label="Hidden word"><span>?</span><span>?</span><span>?</span><span>?</span><span>?</span></div><p class="mistakes" id="mistakes">Choose your difficulty and give it a guess.</p></div></div>
<div class="keyboard" id="keyboard" aria-label="Letter keyboard"></div><div class="game-result" id="hangman-result" role="status"></div></div>
<div id="blackjack-view" hidden><div class="felt"><div class="table-label">DEALER <span id="dealer-total"></span></div><div class="hand dealer-hand" id="dealer-cards"><div class="playing-card back"></div><div class="playing-card back"></div></div><div class="table-mark">BLACKJACK PAYS 3:2<small>DEALER STANDS ON ALL 17s</small></div><div id="player-hands" class="player-hands"><div><div class="hand"><div class="playing-card ghost">♠</div><div class="playing-card ghost">♣</div></div><div class="table-label">YOUR HAND</div></div></div><div class="shoe-label">6 DECKS · PLAY CHIPS ONLY</div></div><div class="game-result" id="blackjack-result" role="status"></div><button id="review-result" class="text-button" hidden>View round result ↗</button><div class="blackjack-actions" id="blackjack-actions"><button class="button primary" id="blackjack-start">Deal me in <span>↗</span></button><button class="button secondary" data-action="hit" disabled>Hit</button><button class="button secondary" data-action="stand" disabled>Stand</button><button class="button secondary" data-action="double" disabled>Double</button><button class="button secondary" data-action="split" disabled>Split</button></div></div>
<div id="daily-view" hidden><div class="daily-meta"><span id="daily-date">Today's puzzle</span><span id="daily-reset">New word at 00:00 UTC</span></div><div class="daily-board" id="daily-board" role="group" aria-label="Daily word guesses"></div><p id="daily-feedback" role="status">One word. Six guesses. A fresh start every day.</p><form id="daily-form"><label class="sr-only" for="daily-input">Your five-letter guess</label><input id="daily-input" maxlength="5" pattern="[A-Za-z]{5}" placeholder="YOUR GUESS" autocomplete="off" autocapitalize="characters" spellcheck="false"><button class="button primary" id="daily-submit">Guess</button></form><div class="keyboard" id="daily-keyboard" aria-label="Daily word keyboard"></div><button id="daily-start" class="button primary">Play today's word ↗</button></div>
<div id="tictactoe-view" hidden><div class="ttt-players"><span><b class="ttt-x">X</b> You</span><span><b class="ttt-o">O</b> Computer</span></div><p id="ttt-status" class="ttt-status" role="status">Three in a row. Make your move.</p><div id="ttt-board" class="ttt-board" role="group" aria-label="Tic Tac Toe board"></div><div class="ttt-controls"><button id="ttt-start" class="button primary">Let’s play ↗</button><span id="ttt-allowance"></span></div></div>
<div id="error" class="error" role="alert" hidden></div></div>
<aside><div id="hangman-settings" @if($game!=='hangman') hidden @endif><p class="eyebrow">MAKE IT YOUR GAME</p><h3>A little challenge?</h3><fieldset id="difficulty"><legend>Choose your difficulty</legend><label><input type="radio" name="difficulty" value="easy" checked><span><strong>Easy</strong><small>Familiar words · 8 misses</small></span><span class="difficulty-dots">●○○</span></label><label><input type="radio" name="difficulty" value="medium"><span><strong>Medium</strong><small>A bit trickier · 7 misses</small></span><span class="difficulty-dots">●●○</span></label><label><input type="radio" name="difficulty" value="hard"><span><strong>Hard</strong><small>Big words · 6 misses</small></span><span class="difficulty-dots">●●●</span></label></fieldset><div class="how-to"><h4>How to play</h4><p>Guess one letter at a time to reveal the word. Every wrong guess adds to the figure. Solve it before your guesses run out.</p></div></div>
<div id="blackjack-settings" hidden><p class="eyebrow">A SEAT AT THE TABLE</p><h3>Get close to 21.</h3><div class="rule-stat"><span>Starting stake</span><strong>10 chips / hand</strong></div><div class="rule-stat"><span>Blackjack pays</span><strong>3 : 2</strong></div><div class="how-to"><h4>Your next move</h4><p><b>Hit</b> takes another card. <b>Stand</b> keeps your total. <b>Double</b> doubles your stake for one final card. <b>Split</b> separates a matching pair.</p></div><details><summary>All house rules</summary><p>Six decks. Dealer peeks for blackjack and stands on soft 17. Aces count as 1 or 11; face cards as 10. Ties push. Double on any first two cards, including after splitting. Split equal-value cards into up to four hands. Split aces get one card each and cannot be split again. Split 21 pays 1:1. No insurance or surrender. Shoe reshuffles below 78 cards, between rounds. Every deal is one play, including splits.</p></details></div>
<div id="daily-settings" hidden><p class="eyebrow">A LITTLE DAILY RITUAL</p><h3>Five letters.<br>Six chances.</h3><div class="how-to"><h4>Find today's word</h4><p>Enter a five-letter word. Each guess gives you clues for the next one.</p></div><div class="word-legend"><p><span class="tile correct">A</span>Right letter, right place</p><p><span class="tile present">R</span>Right letter, different place</p><p><span class="tile absent">T</span>Not in the word</p></div><p class="daily-rules">Everyone gets the same word. A new puzzle arrives at midnight UTC. Your progress is saved in this browser.</p><p class="daily-rules">Five daily puzzles free, then your $1 pass unlocks daily access alongside every game. One puzzle per day, even with a pass.</p></div>
<div id="tictactoe-settings" hidden><p class="eyebrow">THE THREE-IN-A-ROW CLASSIC</p><h3>A small board.<br>A clever next move.</h3><div class="how-to"><h4>How to play</h4><p>You are X and go first. Pick an empty square; the computer plays O. Get three of your marks in a row, column, or diagonal to win.</p></div><div class="how-to"><h4>No space left?</h4><p>If the board fills without a winner, it’s a draw. A completed board counts as one game, whatever the result.</p></div><p class="daily-rules">An unfinished game is saved when you leave. Five games free, then unlimited play with your $1 pass.</p></div>
<div id="fade-settings" hidden><p class="eyebrow">NO DRAWS. JUST SECOND CHANCES.</p><h3>Old moves fade.<br>New chances appear.</h3><div class="how-to"><h4>Three in a row still wins</h4><p>You play X, the computer plays O. A row, column, or diagonal of three ends the game immediately.</p></div><div class="how-to"><h4>A full board isn’t the end</h4><p>If neither side wins, the oldest two Xs and oldest two Os fade away automatically. All other marks stay in place. The next player takes their turn, and the cycle repeats until someone wins.</p></div><p class="daily-rules">Each fade clears four marks, not the whole board. All cycles are part of one game and use just one free play.</p></div>
<div class="access-card"><div class="access-card-top"><span>THE FOREVER PASS</span><span>✳</span></div><h3>More play.<br>Just <span>$1.</span></h3><p>All games. One pass.<br>One payment. All yours.</p><button class="text-button" data-unlock>Unlock your arcade <span>↗</span></button></div></aside></section>
<div class="bottom-note"><span>Made for the joy of playing.</span><span>No downloads. No real-money betting. Just games.</span></div>
</main><footer><span>© {{ date('Y') }} Pocket Arcade</span><button class="text-button" id="restore-open">Restore a purchase</button></footer>
@include('access')
<dialog id="result-dialog" class="result-dialog" aria-labelledby="result-title" aria-describedby="result-description">
<button id="result-close" class="dialog-close" aria-label="Close round result">×</button>
<div class="result-emblem" id="result-emblem" aria-hidden="true">♠</div>
<p class="eyebrow">ROUND COMPLETE</p><h2 id="result-title"></h2>
<div class="result-amount" id="result-amount"></div><p id="result-description"></p>
<div class="result-breakdown" id="result-breakdown"></div>
<p class="result-footnote">Play chips only · No cash value</p>
<button id="result-next" class="button primary wide" autofocus>Deal again ↗</button>
<button id="result-review" class="text-button result-review">Back to the table</button>
</dialog>
</body></html>